// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8iKkmuLtGn-5TIeRE9AzshQkbY_8RZl0',
    appId: '1:74548158138:web:32948e888284c0b6456c83',
    messagingSenderId: '74548158138',
    projectId: 'finora-505ba',
    authDomain: 'finora-505ba.firebaseapp.com',
    storageBucket: 'finora-505ba.firebasestorage.app',
    measurementId: 'G-KN671YVLXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bRJAbqTAVVwIIyPX90m3YvJT0Qgh8-g',
    appId: '1:74548158138:android:06d439f2fbadcaac456c83',
    messagingSenderId: '74548158138',
    projectId: 'finora-505ba',
    storageBucket: 'finora-505ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTaxg-E5FCPGi7Hd6ACkSSP8sZGWa7AJE',
    appId: '1:74548158138:ios:4a3b5535886e382c456c83',
    messagingSenderId: '74548158138',
    projectId: 'finora-505ba',
    storageBucket: 'finora-505ba.firebasestorage.app',
    iosBundleId: 'com.finora.finora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTaxg-E5FCPGi7Hd6ACkSSP8sZGWa7AJE',
    appId: '1:74548158138:ios:4a3b5535886e382c456c83',
    messagingSenderId: '74548158138',
    projectId: 'finora-505ba',
    storageBucket: 'finora-505ba.firebasestorage.app',
    iosBundleId: 'com.finora.finora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8iKkmuLtGn-5TIeRE9AzshQkbY_8RZl0',
    appId: '1:74548158138:web:40d18c741b341d17456c83',
    messagingSenderId: '74548158138',
    projectId: 'finora-505ba',
    authDomain: 'finora-505ba.firebaseapp.com',
    storageBucket: 'finora-505ba.firebasestorage.app',
    measurementId: 'G-E70DW91JCF',
  );
}
